run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-blank: false

issues:
  exclude-rules:
    # Ignore errcheck for fmt.Sscanf - intentionally ignored for best-effort parsing
    - path: internal/server/storage\.go
      linters:
        - errcheck
      text: "Error return value of `fmt.Sscanf` is not checked"

    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0
